# Generated by Django 4.2.18 on 2025-01-17 23:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pelicula',
            name='genero',
            field=models.CharField(choices=[('Ciencia Ficción', 'ciencia ficción'), ('Terror', 'terror'), ('Suspenso', 'suspenso'), ('Romantica', 'romantica'), ('Comedia', 'comedia'), ('Acción', 'acción'), ('Drama', 'drama'), ('Crimen', 'crimen'), ('Animación', 'animación')], max_length=100),
        ),
    ]
