# Generated by Django 4.2.18 on 2025-01-18 00:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0002_alter_pelicula_genero'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='transaccion',
            options={'permissions': (('development', 'Puede desarrollar'), ('scrum_master', 'Es Scrum Master'), ('visualizar_listado', 'visualizar listado'), ('superuser', 'superuser')), 'verbose_name': 'Inventario', 'verbose_name_plural': 'Inventarios'},
        ),
    ]
